platform :ios, '17.0'

use_frameworks!

target 'iosApp' do
    platform :ios, '17.0'
    pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.0"
          end
        end

    installer.pods_project.targets.each do |target|
      if target.name == 'composeApp'
        target.build_configurations.each do |config|
          config.build_settings.delete('ASSETCATALOG_COMPILER_APPICON_NAME')
        end
      end
    end

#     xcframework_path = "#{installer.sandbox.root}/smaato-ios-sdk/vendor"
#
#     Dir.glob("#{xcframework_path}/**/*.framework/OMSDK_Smaato").each do |binary|
#         if File.exist?(binary)
#           puts "Stripping bitcode from: #{binary}"
#           system("xcrun bitcode_strip #{binary} -r -o #{binary}")
#         end
#     end
end
