use_frameworks!

target 'iosApp' do
    platform :ios, '17.0'
    pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'composeApp'
        target.build_configurations.each do |config|
          config.build_settings.delete('ASSETCATALOG_COMPILER_APPICON_NAME')
        end
      end
    end
end