[versions]

ios-deployment-target = "17.0"

firebase = "11.13.0"
google-mobile-ads-ios = "12.5.0"

appodeal-sdk = "3.5.2"
appodeal-amazon-adapter = "3.5.2.0"
appodeal-applovin-adapter = "3.5.2.0"
appodeal-applovin-max-adapter = "3.5.2.0"
appodeal-bid-machine-adapter = "3.5.2.0"
appodeal-bidon-adapter-main = "3.5.2.0"
appodeal-bigo-ads-adapter = "3.5.2.0"
appodeal-dt-exchange-adapter = "3.5.2.0"
appodeal-facebook-adapter = "3.5.2.0"
appodeal-firebase-adapter = "3.5.2.0"
appodeal-admob-adapter = "3.5.2.0"
appodeal-iab-adapter = "3.5.2.0"
appodeal-inmobi-adapter = "3.5.2.0"
appodeal-ironsource-adapter = "3.5.2.0"
appodeal-levelplay-adapter = "3.5.2.0"
appodeal-meta-audience-network-adapter = "3.5.2.0"
appodeal-mintegral-adapter = "3.5.2.0"
appodeal-mytarget-adapter = "3.5.2.0"
appodeal-pangle-adapter = "3.5.2.0"
appodeal-sentry-adapter = "3.5.2.0"
appodeal-smaato-adapter = "3.5.2.0"
appodeal-unity-adapter = "3.5.2.0"
appodeal-vungle-adapter = "3.5.2.0"
appodeal-yandex-adapter = "3.5.2.0"
appodeal-applovin-mediation-amazon-ad-marketplace-adapter = "5.0.1.0"
appodeal-applovin-mediation-bid-machine-adapter = "3.2.0.0.0"
appodeal-applovin-mediation-bigo-ads-adapter = "4.6.0.0"
appodeal-applovin-mediation-bytedance-adapter = "6.4.1.2.0"
appodeal-applovin-mediation-chartboost-adapter = "9.8.0.0"
appodeal-applovin-mediation-facebook-adapter = "6.16.0.0"
appodeal-applovin-mediation-fyber-adapter = "8.3.5.0"
appodeal-applovin-mediation-google-ad-manager-adapter = "12.2.0.0"
appodeal-applovin-mediation-google-adapter = "12.2.0.0"
appodeal-applovin-mediation-inmobi-adapter = "10.8.0.0"
appodeal-applovin-mediation-ironsource-adapter = "8.7.0.0.0"
appodeal-applovin-mediation-mintegral-adapter = "7.7.6.0.0"
appodeal-applovin-mediation-mobile-fuse-adapter = "1.8.2.0"
appodeal-applovin-mediation-moloco-adapter = "3.6.0.0"
appodeal-applovin-mediation-mytarget-adapter = "5.25.1.0"
appodeal-applovin-mediation-ogury-presage-adapter = "5.0.2.0"
appodeal-applovin-mediation-smaato-adapter = "22.9.2.0"
appodeal-applovin-mediation-unity-ads-adapter = "4.13.1.0"
appodeal-applovin-mediation-verve-adapter = "3.1.4.0"
appodeal-applovin-mediation-vungle-adapter = "7.4.4.0"
appodeal-applovin-mediation-yandex-adapter = "5.2.1.0"
appodeal-bid-machine-amazon-adapter = "3.2.0.0"
appodeal-bid-machine-meta-audience-adapter = "3.2.0.0"
appodeal-bid-machine-mintegral-adapter = "3.2.0.0"
appodeal-bid-machine-mytarget-adapter = "3.2.0.0"
appodeal-bid-machine-pangle-adapter = "3.2.0.0"
appodeal-bid-machine-vungle-adapter = "3.2.0.0"
appodeal-bidon-adapter-amazon = "0.7.15.0"
appodeal-bidon-adapter-applovin = "0.7.15.0"
appodeal-bidon-adapter-bid-machine = "0.7.15.0"
appodeal-bidon-adapter-bigo-ads = "0.7.15.0"
appodeal-bidon-adapter-chartboost = "0.7.15.0"
appodeal-bidon-adapter-dt-exchange = "0.7.15.0"
appodeal-bidon-adapter-inmobi = "0.7.15.0"
appodeal-bidon-adapter-ironsource = "0.7.15.0"
appodeal-bidon-adapter-meta-audience-network = "0.7.15.0"
appodeal-bidon-adapter-mintegral = "0.7.15.0"
appodeal-bidon-adapter-mobile-fuse = "0.7.15.0"
appodeal-bidon-adapter-mytarget = "0.7.15.0"
appodeal-bidon-adapter-unity-ads = "0.7.15.0"
appodeal-bidon-adapter-vungle = "0.7.15.0"
appodeal-bidon-adapter-yandex = "0.7.15.0"
appodeal-ironsource-aps-adapter = "4.3.18.0"
appodeal-ironsource-admob-adapter = "4.3.63.0"
appodeal-ironsource-applovin-adapter = "4.3.52.0"
appodeal-ironsource-bid-machine-adapter = "4.3.14.0"
appodeal-ironsource-bigo-adapter = "4.3.4.0"
appodeal-ironsource-facebook-adapter = "4.3.47.0"
appodeal-ironsource-fyber-adapter = "4.3.41.0"
appodeal-ironsource-inmobi-adapter = "4.3.26.0"
appodeal-ironsource-mintegral-adapter = "4.3.32.0"
appodeal-ironsource-mobile-fuse-adapter = "4.3.5.0"
appodeal-ironsource-moloco-adapter = "4.3.10.0"
appodeal-ironsource-mytarget-adapter = "4.1.27.0"
appodeal-ironsource-ogury-adapter = "4.3.3.0"
appodeal-ironsource-pangle-adapter = "4.3.39.0"
appodeal-ironsource-smaato-adapter = "4.3.16.0"
appodeal-ironsource-unity-ads-adapter = "4.3.47.0"
appodeal-ironsource-verve-adapter = "4.3.4.0"
appodeal-ironsource-vungle-adapter = "4.3.42.0"

revenuecat = "13.32.0"

mixpanel = "5.0.8"
facebook = "18.0.0"