[versions]
agp = "8.9.3"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"
gradle-versions = "0.52.0"
build-konfig = "0.17.1"
google-services = "4.4.2"
firebase-crashlytics = "3.0.3"

app-version-year = "25"
app-version-month = "05"
app-version-date = "27"
app-version-build = "3"

android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"

kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
kotlinx-io = "0.7.0"
kotlinx-datetime = "0.6.2"

kermit = "2.0.5"
koin = "4.0.4"
ktor = "3.1.3"
settings = "1.3.0"
coil = "3.2.0"
ksoup = "0.5.0"

androidx-activity-compose = "1.10.1"

androidx-core-ktx = "1.16.0"
androidx-lifecycle = "2.8.4"
androidx-lifecycle-jb = "2.8.4"
androidx-room = "2.7.1"
androidx-sqlite = "2.5.1"
androidx-credentials = "1.5.0"

google-identity-google-id = "1.1.1"

compose-multiplatform = "1.8.0" # 1.8.1+ requires newer koin, which requires migration of navType
compose-material-icons = "1.7.3"

firebase-android-bom = "33.14.0"

appodeal-sdk-android = "3.6.0.0"

revenuecat = "1.8.0+13.32.0"

amplitude-android = "1.21.1"
mixpanel-android = "8.1.0"
facebook-sdk-android-core = "18.0.3"
facebook-sdk-android-marketing = "7.0.1"
kochava-android = "5.6.0"

play-services-ads-id = "18.2.0"
play-services-app-set = "16.1.0"
android-install-referrer = "2.2"

rebugger = "1.0.0-rc03"

androidx-espresso-core = "3.6.1"
androidx-test-junit = "1.2.1"
junit = "4.13.2"
mockk = "1.14.2"
turbine = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle-jb" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-jb" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-jb" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }

compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "compose-material-icons" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

firebase-android-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-android-bom" }
firebase-android-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-android-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-android-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-android-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-android-auth = { module = "com.google.firebase:firebase-auth" }
firebase-android-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }

androidx-credentials-main = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
google-identity-google-id = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-identity-google-id" }

ksoup-html = { module = "com.mohamedrejeb.ksoup:ksoup-html", version.ref = "ksoup" }

appodeal-sdk-android = { module = "com.appodeal.ads:sdk", version.ref = "appodeal-sdk-android" }

revenuecat-purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "revenuecat" }
revenuecat-purchases-ui = { module = "com.revenuecat.purchases:purchases-kmp-ui", version.ref = "revenuecat" }
revenuecat-purchases-datetime = { module = "com.revenuecat.purchases:purchases-kmp-datetime", version.ref = "revenuecat" }

amplitude-android = { module = "com.amplitude:analytics-android", version.ref = "amplitude-android" }
mixpanel-android = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel-android" }

facebook-sdk-android-core = { module = "com.facebook.android:facebook-core", version.ref = "facebook-sdk-android-core" }
facebook-sdk-android-marketing = { module = "com.facebook.android:facebook-marketing", version.ref = "facebook-sdk-android-marketing" }

kochava-android-tracker = { module = "com.kochava.tracker:tracker", version.ref = "kochava-android" }
kochava-android-events = { module = "com.kochava.tracker:events", version.ref = "kochava-android" }
kochava-android-datapoints = { module = "com.kochava.tracker:datapointnetwork", version.ref = "kochava-android" }

play-services-ads-id = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "play-services-ads-id" }
play-services-app-set = { module = "com.google.android.gms:play-services-appset", version.ref = "play-services-app-set" }
android-install-referrer = { module = "com.android.installreferrer:installreferrer", version.ref = "android-install-referrer" }

rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }

build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }